### ISSUE TITLE
HasManyThrough relation - Error: Invalid relation type: undefined

### ISSUE THREAD

**Issue by amismailz** [exromany/loopback-counts-mixin#12]
I have the following relation,
file: grade.json
```
"relations": {
    "students": {
      "type": "hasMany",
      "model": "Account",
      "foreignKey": "gradeId",
      "through": "Family",
      "keyThrough": "studentId"
    },
    "mixins": {
      "Counts": true
    }
  }
```
Any request to /grades gives the following response:
```json
{
    "error": {
        "statusCode": 500,
        "name": "AssertionError [ERR_ASSERTION]",
        "message": "Invalid relation type: undefined",
        "generatedMessage": false,
        "code": "ERR_ASSERTION",
        "actual": false,
        "expected": true,
        "operator": "==",
        "stack": "AssertionError [ERR_ASSERTION]: Invalid relation type: undefined\n    at validateRelation (/api/node_modules/loopback-datasource-juggler/lib/datasource.js:549:3)\n    at /api/node_modules/loopback-datasource-juggler/lib/datasource.js:515:7\n    at Array.forEach (<anonymous>)\n    at DataSource.defineRelations (/api/node_modules/loopback-datasource-juggler/lib/datasource.js:511:28)\n    at DataSource.setupDataAccess (/api/node_modules/loopback-datasource-juggler/lib/datasource.js:648:8)\n    at DataSource.attach (/api/node_modules/loopback-datasource-juggler/lib/datasource.js:882:8)\n    at Function.ModelClass.attachTo (/api/node_modules/loopback-datasource-juggler/lib/model-builder.js:382:16)\n    at /api/server/server.js:57:29\n    at Layer.handle [as handle_request] (/api/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/api/node_modules/express/lib/router/index.js:317:13)\n    at /api/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/api/node_modules/express/lib/router/index.js:335:12)\n    at next (/api/node_modules/express/lib/router/index.js:275:10)\n    at nosniff (/api/node_modules/dont-sniff-mimetype/index.js:4:5)\n    at Layer.handle [as handle_request] (/api/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/api/node_modules/express/lib/router/index.js:317:13)"
    }
}
```

**Comment by arjamizo** [comment]
you need to put mixing one level higher, it has to be a sibling of `name`, `properties` and `relations`, not inside relations

btw. this is not a FAQ section, but issues with the library itself, not with using it.
